FROM node:18.17.1-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
RUN npm install
RUN npm install react-scripts@5.0.1 -g
COPY . ./
ENV PUBLIC_URL /client/
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html/client
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

WORKDIR /usr/share/nginx/html/client
COPY ./env.sh .
RUN apk add --no-cache bash
RUN chmod +x env.sh
